version: "3.6"

services:
    db:
        image: postgres:11-alpine
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: dev
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: dev
        ports:
            - "5432:5432"
volumes:
    postgres-data: